In [1]:
#importing library
import pandas as pd

In [4]:
#create dataframe
df=pd.DataFrame({
    'Name':['Bhavya','Reema','Anjali','Janvi'],
    'Maths':[100,80,90,95],
    'Science':[90,94,95,99],
    'English':[95,98,92,100],
    'Computer Science':[100,70,99,100]
})
df

     Name  Maths  Science  English  Computer Science
0  Bhavya    100       90       95               100
1   Reema     80       94       98                70
2  Anjali     90       95       92                99
3   Janvi     95       99      100               100

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              4 non-null      object
 1   Maths             4 non-null      int64
 2   Science           4 non-null      int64
 3   English           4 non-null      int64
 4   Computer Science  4 non-null      int64
dtypes: int64(4), object(1)
memory usage: 292.0+ bytes

In [6]:
df.describe()

            Maths    Science  English  Computer Science
count    4.000000   4.000000     4.00          4.000000
mean    91.250000  94.500000    96.25         92.250000
std      8.539126   3.696846     3.50         14.840822
min     80.000000  90.000000    92.00         70.000000
25%     87.500000  93.000000    94.25         91.750000
50%     92.500000  94.500000    96.50         99.500000
75%     96.250000  96.000000    98.50        100.000000
max    100.000000  99.000000   100.00        100.000000